apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-demo
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
